### PR TITLE
Set Icepack as the default column physics package in MPAS-SI

### PR DESCRIPTION
**Pull request by eclare108213**
Change the default value of `config_column_physics_type` from `column_package` to `icepack`.
BFB in 3-month D cases.

### CODE REVIEW

**Review by proteanplanet — APPROVED** [review]
For years 0001-0098, fully coupled v3alph04 in E3SM, Icepack is statistically identical to ColPkg at the 99% compatibility interval for the same configuration:

E3SM_sea_ice_lemnisc 0001-0098 ColPkg Icepack PI extent volume snow 3

Daily sea ice phase average (solid) and interquartile range (gray). Dashed red lines indicate the null hypothesis for days of the year that Icepack is different from ColPkg at the 99% compatibility interval. Traces start on January 1, passing the northward equinox (•), northern solstice (◦), southward equinox (•), and southern solstice (◦) to the end of December (→).

Approved

**Review by njeffery — APPROVED** [review]
Approved based on single-column tests contrasting Icepack and column_package.

**Review by jonbob — APPROVED** [review]

**Review by darincomeau — APPROVED** [review]
Approved based on other's testing

**Review by erinethomas — APPROVED** [review]
approved.

**Pull request merged**
