### PR TITLE
Update to E3SM master

### PR DESCRIPTION
**Pull request by eclare108213**
Bringing in all changes from E3SM master since the last update, https://github.com/eclare108213/E3SM/pull/2.  
Tested in 3-month D-case runs: 

> --- Average Field and Global Differences for Month 03, Year 0001:
> 
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil k000 - 
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil k001:
> 
> 			Minimum 	Maximum
>     iceAreaCell: 	-1.51177e-02 	+4.77356e-03
>     iceVolumeCell: 	-8.79821e-03 	+2.27110e-02
>     icePressure: 	-2.23776e+03 	+1.24779e+03
>     uVelocityGeo: 	-3.41903e-03 	+6.33866e-03
>     vVelocityGeo: 	-2.77237e-03 	+1.76409e-03
> 
> 			North 		South
>     IceExtent:  	-8.93207e+01 	+5.92936e+02
>     IceVolume:  	-2.18409e-02 	+1.90506e+00
>     SnowVolume:  	+3.59590e-03 	+1.22437e-02
>     KineticEnergy:  	+2.10704e+09 	+4.42736e+10
> 
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil k000 - 
>     D3.nset01.therm1.vertical_thermo.eclare108213.anvil k000:
> 
>     iceAreaCell:  	BFB
>     iceVolumeCell:  	BFB
>     icePressure:  	BFB
>     uVelocityGeo:  	BFB
>     vVelocityGeo:  	BFB
> 
>     IceExtent:  	BFB
>     IceVolume:  	BFB
>     SnowVolume:  	BFB
>     KineticEnergy:  	BFB
> 
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil k000 - 
>     D3.nset01.therm1.vertical_thermo.eclare108213.anvil k001:
> 
> 			Minimum 	Maximum
>     iceAreaCell: 	-1.51177e-02 	+4.77356e-03
>     iceVolumeCell: 	-8.79821e-03 	+2.27110e-02
>     icePressure: 	-2.23776e+03 	+1.24779e+03
>     uVelocityGeo: 	-3.41903e-03 	+6.33866e-03
>     vVelocityGeo: 	-2.77237e-03 	+1.76409e-03
> 
> 			North 		South
>     IceExtent:  	-8.93207e+01 	+5.92936e+02
>     IceVolume:  	-2.18409e-02 	+1.90506e+00
>     SnowVolume:  	+3.59590e-03 	+1.22437e-02
>     KineticEnergy:  	+2.10704e+09 	+4.42736e+10
> 
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil k001 - 
>     D3.nset01.therm1.vertical_thermo.eclare108213.anvil k000:
> 
> 			Minimum 	Maximum
>     iceAreaCell: 	-4.77356e-03 	+1.51177e-02
>     iceVolumeCell: 	-2.27110e-02 	+8.79821e-03
>     icePressure: 	-1.24779e+03 	+2.23776e+03
>     uVelocityGeo: 	-6.33866e-03 	+3.41903e-03
>     vVelocityGeo: 	-1.76409e-03 	+2.77237e-03
> 
> 			North 		South
>     IceExtent:  	+8.93207e+01 	-5.92936e+02
>     IceVolume:  	+2.18409e-02 	-1.90506e+00
>     SnowVolume:  	-3.59590e-03 	-1.22437e-02
>     KineticEnergy:  	-2.10704e+09 	-4.42736e+10
> 
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil k001 - 
>     D3.nset01.therm1.vertical_thermo.eclare108213.anvil k001:
> 
>     iceAreaCell:  	BFB
>     iceVolumeCell:  	BFB
>     icePressure:  	BFB
>     uVelocityGeo:  	BFB
>     vVelocityGeo:  	BFB
> 
>     IceExtent:  	BFB
>     IceVolume:  	BFB
>     SnowVolume:  	BFB
>     KineticEnergy:  	BFB
> 
>     D3.nset01.therm1.vertical_thermo.eclare108213.anvil k000 - 
>     D3.nset01.therm1.vertical_thermo.eclare108213.anvil k001:
> 
> 			Minimum 	Maximum
>     iceAreaCell: 	-1.51177e-02 	+4.77356e-03
>     iceVolumeCell: 	-8.79821e-03 	+2.27110e-02
>     icePressure: 	-2.23776e+03 	+1.24779e+03
>     uVelocityGeo: 	-3.41903e-03 	+6.33866e-03
>     vVelocityGeo: 	-2.77237e-03 	+1.76409e-03
> 
> 			North 		South
>     IceExtent:  	-8.93207e+01 	+5.92936e+02
>     IceVolume:  	-2.18409e-02 	+1.90506e+00
>     SnowVolume:  	+3.59590e-03 	+1.22437e-02
>     KineticEnergy:  	+2.10704e+09 	+4.42736e+10
> 
> --- Case root: /lcrc/group/e3sm/ac.eclare/E3SM-Polar/
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil
> 
> --- Code root: ~/E3SM-Polar/code/updateE3SM4
> 
> --- Provenance root: ~/E3SM-Polar/provenance/updateE3SM4/
>     D3.nset01.updateE3SM4.update_E3SM_4.eclare108213.anvil
> 
> --- Script saved: E3SM-Polar-Developer.sh.20230410-192927

### CODE REVIEW

**Comment by eclare108213** [comment]
@jonbob @darincomeau 
I don't expect you to test this (unless you just really want to) - I'm mainly looking for a sanity check that I'm doing it right and have caught everything.  I 'git pull'ed, like I always do, which normally commits all of the changes directly to the branch. I don't understand why these changes are now listed as "not staged for commit":

```
[ac.eclare@blueslogin3 updateE3SM4]$ git status
# On branch update_E3SM_4
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   cime (new commits)
#	modified:   components/eam/src/physics/rrtmgp/external (new commits)
#	modified:   components/elm/src/external_models/fates (new commits)
#	modified:   externals/YAKL (new commits)
#	modified:   externals/kokkos (new commits)
#
no changes added to commit (use "git add" and/or "git commit -a")
```
???

**Comment by jonbob** [comment]
@eclare108213 -- those are all just submodules that have been updated. You may want to add this to your pull command:
````
git pull --recurse-submodules
````
or something like that

**Comment by darincomeau** [comment]
It looks like the cime submodule is in some intermediate state between E3SM/master and [eclare108213/seaice/icepack-integration](https://github.com/eclare108213/E3SM/tree/eclare108213/seaice/icepack-integration). I'm not sure how that happened, but I'd probably start fresh again? I can try myself and see what I get.

EDIT: Opened as a draft PR here: https://github.com/eclare108213/E3SM/pull/15, submodules appear to be correctly updated and `git status` is clean.

**Comment by eclare108213** [comment]
Closing in favor of https://github.com/eclare108213/E3SM/pull/15

**Pull request closed without merging**
