### PR TITLE
Update to E3SM master

### PR DESCRIPTION
**Pull request by eclare108213**
Updates the icepack integration branch in my fork with changes from E3SM master.  Fixed one conflict in mpas_seaice_velocity_solver.F.  BFB in 6-day D smoke test.

### CODE REVIEW

**Comment by eclare108213** [comment]
@darincomeau @apcraig 
Darin and I tried to rebase but that was bringing in commits that should already be in my fork.  Here I've done a pull from e3sm and push to the icepack integration branch, which does not show those commits.  This appears to be cleaner and less confusing (to me at least) than the rebase.  Let me know if you think this is right.  I don't want to set off on the wrong foot...

**Comment by darincomeau** [comment]
Tagging @jonbob also since he'll be the one integrating this into `e3sm/master`.

>Darin and I tried to rebase but that was bringing in commits that should already be in my fork.

Just to clarify, the rebase replays the commits in your branch on top of `e3sm/master`, so the commits aren't duplicated, but rather the originals are 'lost' as the history is rewritten.

The code here should be the same as what we did in the rebase, it's just the history that looks very different. Here all of the new e3sm commits are at the top of the history, and this branch's commits are much further down. I don't think it matters too much now as this is a working branch, and we still have the PR records of everything that's going in. When we actually open a PR into `e3sm/master`, we'll need to do a rebase at that point, so there's a clean history of all the commits we're actually bringing in at the top. That step may involve re-resolving conflicts (I'm not totally sure; actually, I'm pretty sure). 

Having said all that, keeping this branch up to date with `e3sm/master` this way (merge rather than rebase) is good with me.

**Review by darincomeau — APPROVED** [review]

**Comment by eclare108213** [comment]
After this is merged, I'll update the icepack pointer to the latest version on the E3SM-Project/Icepack cice-consortium/e3sm-icepack-initial-integration branch.  @apcraig can I help with the rsnow fix?  We're manually commenting out those lines at the moment, would be good to get that into my fork soon.

**Comment by eclare108213** [comment]
I still have the other branch on which we did the rebase, and we can use that one instead if @jonbob prefers.  Fixing a bunch of conflicts at the end of the process would be rather aggravating.

**Comment by darincomeau** [comment]
>Fixing a bunch of conflicts at the end of the process would be rather aggravating.

I think that this is going to be unavoidable unfortunately. Even if we rebase now, rebasing later will still involve re-resolving conflicts, as it replays all of the commits. At least thats what I *think* will happen.
Also rebasing would require loosening branch protections for the force push, which I completely understand wanting to keep in place.

**Comment by jonbob** [comment]
@eclare108213 - how many conflicts did you run into? There wasn't much done in the seaice code recently, so it should have been minimal

**Comment by darincomeau** [comment]
@jonbob the conflict arose from the renaming of `block` to `blockPtr` from this: https://github.com/E3SM-Project/E3SM/pull/5290

**Comment by apcraig** [comment]
I agree with @darincomeau, If you rebase later, the rebase is going to request the conflicts be resolved again one commit at a time.  The other option is that you just keep this merge branch going forward and when you PR to E3SM main, you squash merge it.   Would that preserve the main history and just add the new changes?  Is squash merging allowed/encouraged in E3SM?

**Comment by eclare108213** [comment]
There was only one small conflict this time, but I imagine there will be others as we bring in other Icepack modules.  Adrian is actively changing the dynamics code, which shouldn't conflict _much_ with our changes in Icepack.  My preference is pull/push rather than rebase, all things considered, unless this isn't okay with E3SM more generally.

**Comment by jonbob** [comment]
@eclare108213 - there are no other seaice PRs on the horizon, as far as I know. I'm happy to take care of conflicts when I merge this to master, if you would rather not rebase

**Comment by eclare108213** [comment]
Thanks @jonbob.  Then I'll continue down this path, since it's familiar to me and doesn't require --force.

**Pull request merged**
