### PR TITLE
updating Icepack to hash b2b8066

### PR DESCRIPTION
**Pull request by eclare108213**
This update brings in changes from the Consortium that make FSD arguments optional in Icepack's step_therm2 calls.
BFB in D-case tests with prior snicar tests for PR#19.
Tests with debugging flags turned on also ran successfully.

### CODE REVIEW

**Comment by eclare108213** [comment]
Results from the D-case tests comparing icepack with column are here: https://acme-climate.atlassian.net/wiki/spaces/ICE/pages/3537993995/Icepack+Integration+Branch+Status+and+Testing

**Review by apcraig — APPROVED** [review]

**Review by erinethomas — APPROVED** [review]

**Comment by proteanplanet** [comment]
@eclare108213 What testing was conducted with this aside from running with debug flags on?

**Comment by eclare108213** [comment]
@proteanplanet I ran a 3-month D-case comparison of icepack and column, which is entirely BFB with the previous such comparison using the same namelist configuration (snicar turned on) -- see link in the comment above to view the results.  The icepack changes were also tested in the Consortium's full test suites, and were BFB there.

**Comment by proteanplanet** [comment]
I'm not officially a reviewer, but I approve!

**Pull request merged**
