### PR TITLE
Icepack integration merge 20230920

### PR DESCRIPTION
**Pull request by darincomeau**
Updates E3SM to master on 20230920.

### CODE REVIEW

**Comment by darincomeau** [comment]
Running a `SMS.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel` test now, will update comment with status.

EDIT: I'm getting build errors with both intel and gnu, initial error message isn't instructive.

**Comment by eclare108213** [comment]
Thanks @darincomeau !

**Comment by proteanplanet** [comment]
Minor comment while I review this:  Update your starting comment from "Updates E3SM to master on 202309**30**" to "Updates E3SM to master on 20230920"

**Comment by darincomeau** [comment]
I'll note there was a conflict in `components/mpas-seaice/src/shared/mpas_seaice_constants.F` at the end of the file with the adding about 10-20 ocean BGC constants, and changing two existing constants to defined parameters.  If someone could take a look at that as part of review to make sure that's correct that would be great.

**Comment by eclare108213** [comment]
The change to mpas_seaice_constants.F looks okay to me, but @njeffery should confirm.

**Comment by darincomeau** [comment]
I'm getting build errors on multiple machines, configurations, compilers, so something is broken here.

**Comment by proteanplanet** [comment]
> I'm getting build errors on multiple machines, configurations, compilers, so something is broken here.

I cannot get this to compile either.

**Comment by proteanplanet** [comment]
In src/shared/mpas_seaice_constants.F, the following lines should be changed:

   ! biogeochemistry constants
   real(kind=RKIND), parameter, public :: &
        skeletalLayerThickness = sk_l      , &
        gramsCarbonPerMolCarbon = R_gC2molC    ! g carbon per mol carbon

Need to be changed to:

   ! biogeochemistry constants
   real(kind=RKIND), public :: &
        skeletalLayerThickness, &    
        gramsCarbonPerMolCarbon

**Comment by proteanplanet** [comment]
With the above commit I just added, this is the difference between Icepack and the column_package for parallel 3-month D-cases:


```
		            Minimum 	Maximum
    iceAreaCell: 	-4.71747e-03 	+1.08661e-02
    iceVolumeCell: 	-3.98719e-02 	+1.21286e-02
    icePressure: 	-2.44173e+03 	+2.36390e+03
    uVelocityGeo: 	-1.35535e-03 	+1.71776e-03
    vVelocityGeo: 	-7.73802e-04 	+8.95668e-04

			      North 	 South
    totalIceExtent:  	-1.29909e+02 	+6.27066e+02
    totalIceVolume:  	+2.28353e-01 	-1.20611e+00
    totalSnowVolume:  	+2.16794e-02 	-7.75084e-01
    totalKineticEnergy: -5.34257e+09 	-2.09773e+10
    averageAlbedo:  	-3.85015e-06 	-6.47554e-05

```

```
    k000 ->
    mpassi: 	config_column_physics_type = 'column_package'

    k001 ->
    mpassi: 	config_column_physics_type = 'icepack'
```

**Comment by proteanplanet** [comment]
For the default case (column package on), the PEM test fails:

```

  ERS_Ld5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel XML
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=135
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=653
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel RUN time=56
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel (Overall: FAIL) details:
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SHAREDLIB_BUILD time=129
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel MODEL_BUILD time=647
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SUBMIT
    FAIL PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel RUN time=44
    PEND PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel COMPARE_base_modpes
  PET_Ln5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel XML
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=135
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=808
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel RUN time=30
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_single_thread
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 (Overall: PASS) details:
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 CREATE_NEWCASE
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 XML
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SETUP
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SHAREDLIB_BUILD time=83
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 MODEL_BUILD time=349
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SUBMIT
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 RUN time=265
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 MEMLEAK insuffiencient data for memleak test
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SHORT_TERM_ARCHIVER

```

**Comment by proteanplanet** [comment]
I am now checking with the PEM test fails for the current master.

**Comment by eclare108213** [comment]
What do ERS, PEM, PET and SMS stand for?

**Comment by proteanplanet** [comment]
> What do ERS, PEM, PET and SMS stand for?

Exact restart, processor count, threading test, smoke test, respectively.

**Comment by proteanplanet** [comment]
@eclare108213 Please can you run the following test on your fork and branch:

${CODE_ROOT}/cime/scripts/create_test --output-root "${CASE_ROOT}" --machine "${MACHINES[${MACH}]}"  --project "${PROJECTS[${MACH}]}" --wait PEM_Ln5.T62_oQU240wLI.DTESTM 

Use MACHINES=("anvil" "chrysalis"), depending on your choice, and then the respective PROJECTS=("condo" "e3sm").

**Comment by proteanplanet** [comment]
Well, there's more to this than meets the eye.   E3SM master fails the PEM test:

20230921_091417_mtlmwo: 4 tests
  ERS_Ld5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel XML
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=132
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=355
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel RUN time=54
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel (Overall: FAIL) details:
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SHAREDLIB_BUILD time=129
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel MODEL_BUILD time=348
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SUBMIT
    FAIL PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel RUN time=42
    PEND PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel COMPARE_base_modpes
  PET_Ln5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel XML
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=135
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=441
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel RUN time=29
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_single_thread
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 (Overall: PASS) details:
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 CREATE_NEWCASE
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 XML
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SETUP
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SHAREDLIB_BUILD time=86
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 MODEL_BUILD time=264
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SUBMIT
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 RUN time=268
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 MEMLEAK insuffiencient data for memleak test
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SHORT_TERM_ARCHIVER

**Comment by eclare108213** [comment]
On the bright side, the icepack-integration branch passed restart, threading, and the smoke test.  I was worried about restarts, and threading could have been issue too.  Yay.

**Comment by eclare108213** [comment]
My fork/branch (prior to this PR) passes on anvil:

```
[ac.eclare@blueslogin4 tracers]$ ./cime/scripts/create_test  --machine "anvil" --project "condo" --wait PEM_Ln5.T62_oQU240wLI.DTESTM
create_test will do up to 1 tasks simultaneously
create_test will use up to 45 cores simultaneously
Creating test directory /lcrc/group/e3sm/ac.eclare/scratch/anvil/PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel.20230921_093515_3i18f6
RUNNING TESTS:
  PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel
Starting CREATE_NEWCASE for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel with 1 procs
Finished CREATE_NEWCASE for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel in 2.307272 seconds (PASS)
Starting XML for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel with 1 procs
Finished XML for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel in 0.690038 seconds (PASS)
Starting SETUP for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel with 1 procs
Finished SETUP for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel in 8.866549 seconds (PASS)
Starting SHAREDLIB_BUILD for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel with 1 procs
Finished SHAREDLIB_BUILD for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel in 325.134320 seconds (PASS)
Starting MODEL_BUILD for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel with 6 procs
Finished MODEL_BUILD for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel in 1253.549191 seconds (PASS)
Starting RUN for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel with 1 proc on interactive node and 144 procs on compute nodes
Finished RUN for test PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel in 4.452867 seconds (PEND). [COMPLETED 1 of 1]
Waiting for tests to finish
PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel RUN
    Case dir: /lcrc/group/e3sm/ac.eclare/scratch/anvil/PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel.20230921_093515_3i18f6
test-scheduler took 1645.864486694336 seconds

```

**Comment by proteanplanet** [comment]
The issue is anvil, and master.  I ran exactly the same test on Chrysalis with master, and everything passed:

20230921_094443_h5e8t3: 4 tests
  ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel XML
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel SETUP
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel SHAREDLIB_BUILD time=196
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel MODEL_BUILD time=912
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel RUN time=31
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel MEMLEAK insuffiencient data for memleak test
    PASS ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel (Overall: PASS) details:
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel SHAREDLIB_BUILD time=195
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel MODEL_BUILD time=902
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel SUBMIT
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel RUN time=31
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel COMPARE_base_modpes
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel MEMLEAK insuffiencient data for memleak test
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel SHORT_TERM_ARCHIVER
  PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel (Overall: PASS) details:
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel XML
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel SETUP
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel SHAREDLIB_BUILD time=198
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel MODEL_BUILD time=899
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel SUBMIT
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel RUN time=15
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel COMPARE_base_single_thread
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel MEMLEAK insuffiencient data for memleak test
    PASS PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel SHORT_TERM_ARCHIVER
  SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 (Overall: PASS) details:
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 CREATE_NEWCASE
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 XML
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 SETUP
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 SHAREDLIB_BUILD time=73
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 MODEL_BUILD time=141
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 SUBMIT
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 RUN time=180
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 MEMLEAK insuffiencient data for memleak test
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.chrysalis_intel.mpassi-jra_1958 SHORT_TERM_ARCHIVER

**Comment by proteanplanet** [comment]
So I'm now going to proceed testing this PR on Chrysalis, and will report back.

**Comment by proteanplanet** [comment]
Yay!

20230921_102326_v4hwrz: 4 tests
  ERS_Ld5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel XML
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=151
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=691
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel RUN time=52
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel (Overall: PASS) details:
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SHAREDLIB_BUILD time=149
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel MODEL_BUILD time=681
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SUBMIT
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel RUN time=46
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel COMPARE_base_modpes
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  PET_Ln5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel XML
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=150
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=861
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel RUN time=29
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_single_thread
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 (Overall: PASS) details:
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 CREATE_NEWCASE
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 XML
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SETUP
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SHAREDLIB_BUILD time=102
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 MODEL_BUILD time=431
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SUBMIT
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 RUN time=267
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 MEMLEAK insuffiencient data for memleak test
    PASS SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 SHORT_TERM_ARCHIVER

--- Testsuite 'e3sm_ice_developer' PASSED for sandbox 'icepackmerge'

**Comment by proteanplanet** [comment]
So e3sm_ice_developer passes for this PR on Anvil.

**Comment by darincomeau** [comment]
Thanks @proteanplanet for finding that build fix! Glad it was just a merge conflict resolution error. And thanks to you and @eclare108213 for all the testing!

**Review by proteanplanet — APPROVED** [review]
Based on results presented here, and passing standard D-case tests, I approve this PR.

**Review by jonbob — APPROVED** [review]
Approved based on testing

**Review by eclare108213 — APPROVED** [review]
approving based on testing so far

**Pull request merged**
